apiVersion: v1
kind: Service
metadata:
  name: fapp-service
spec:
  selector:
    app: fapp
  ports:
    - protocol: TCP
      port: 5173
      nodePort: 30000
      appProtocol: http
      name: back
    - protocol: TCP
      port: 3000
      nodePort: 30001
      appProtocol: http
      name: front
  type: NodePort